spring:
  redis:
    host: redis
    port: 6379
    timeout: 600000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/ 
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8085

management:
  endpoints:
    web:
      exposure:
        include: "*" 
