spring:
  application:
    name: cartservice
  data:
    redis:
      host: localhost
      port: 6379 
server:
  port: 8085
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
  instance:
    instance-id: ${spring.application.name}:${instanceId:${random.value}}
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

