spring:
  datasource:
    url: jdbc:mysql://customerservicedb:5432/customerservicedb
    username: my_user
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"



server:
  port: 8081

