spring:
  application:
    name: customerservice
  datasource:
    url: jdbc:mysql://mysql:3306/customer_db?allowPublicKeyRetrieval=true&useSSL=false
    username: my_user
    password: test
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"



server:
  port: 8080

