spring:
  application:
    name: eureka
server:
  port: 8888
eureka:
  instance:
    hostname: eureka
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"