#spring:
#  application:
#    name: gateway
#  cloud:
#    gateway:
#      mvc:
#        routes:
#          - id: customer-service.routing
#            uri: lb://customerservice # load-balancing
#            predicates:
#              - Path=/api/customers/**
#          - id: product-service.routing
#            uri: lb://productservice
#            predicates:
#              - Path=/api/products/**
#          - id: eureka.routing
#            uri: ${eureka.url}
#            predicates:
#              - Path=/eureka/web
#            filters:
#              - SetPath=/
#          - id: eureka.static-files
#            uri: ${eureka.url}
#            predicates:
#              - Path=/eureka/**

spring:
  application:
    name: gateway
server:
  port: 8090
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://gateway:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

