spring:
  application:
    name: gateway
server:
  port: 8090
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://gateway:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"