spring:
 application:
   name: gateway
 cloud:
   gateway:
     mvc:
       routes:
         - id: customer-service.routing
           uri: lb://customer # load-balancing
           predicates:
             - Path=/api/v1/customer/**
         - id: identity-service.routing
           uri: lb://identity  # load-balancing
           predicates:
             - Path=/api/v1/identity/**
         - id: order-service.routing
           uri: lb://order  # load-balancing
           predicates:
             - Path=/api/v1/order/**
         - id: product-service.routing
           uri: lb://product
           predicates:
             - Path=/api/v1/product/**
         - id: eureka.routing
           uri: ${eureka.url}
           predicates:
             - Path=/eureka/web
           filters:
             - SetPath=/
         - id: eureka.static-files
           uri: ${eureka.url}
           predicates:
             - Path=/eureka/**
server:
  port: 8090

eureka:
  url: http://localhost:8888
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
