spring:
  application:
    name: identityservice
  datasource:
    url: jdbc:postgresql://identityservice.db:5433/identitydb
    username: postgres
    password: test
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        ddl-auto: update
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka:8888/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8083
